	.title	byrout
	.ident	/X00.20/
	.mcall	ordie,die
	.mcall	htmast,htmbgn
	.mcall	tag,respnd,ctx2st,ctxuse,ctxrdy,htmsg

	.psect	da,d,ro
bye::	.asciz	/Goodbye World from RSX-11M-PLUS!/
info::	.asciz	/Visitor #%D. RequestID = %P/

	.psect	ctr,d,rw
infdat::
ctr::	.word	0
reqid::	.word	0

	.psect	main,i,ro
start::	htmast	#rqst

rqst::	htmbgn
	tag	<p>
	respnd	#bye
	tag	</p>
	mov	$$$ctx,r0
	mov	ht.cli(r0),reqid
	htmsg	#info,#infdat
	inc	ctr
	return

	.end	start
